services:
  datadog-agent:
    image: datadog/agent
    env_file:
      - config.env
    links:
      - client-test
      - server-test
    environment:
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  client-test:
    build:
      context: ./client
    environment:
      - SERVER_HOST=server-test

  server-test:
    build:
      context: ./node-server
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_SERVICE=server-test
