services:
  datadog-agent:
    image: datadog/agent
    env_file:
      - config.env
    links:
      - client
      - server
    environment:
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

  client:
    build:
      context: ./client
      args:
        DD_GIT_COMMIT_SHA: ${DD_GIT_COMMIT_SHA:-}
        DD_GIT_REPOSITORY_URL: https://github.com/olivwalsh/datadog-sci-demo
    environment:
      - SERVER_HOST=server
      - DD_GIT_COMMIT_SHA=${DD_GIT_COMMIT_SHA:-}
      - DD_GIT_REPOSITORY_URL=https://github.com/olivwalsh/datadog-sci-demo

  server:
    build:
      context: ./node-server
      args:
        DD_GIT_COMMIT_SHA: ${DD_GIT_COMMIT_SHA:-}
        DD_GIT_REPOSITORY_URL: https://github.com/olivwalsh/datadog-sci-demo
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_VERSION=1.2.6
      - DD_SERVICE=olivia-test
      - DD_GIT_COMMIT_SHA=${DD_GIT_COMMIT_SHA:-}
      - DD_GIT_REPOSITORY_URL=https://github.com/olivwalsh/datadog-sci-demo
